### ISSUE TITLE
Weird behavior when debugging Cosmos Db Distributed Cache with Sessions

### ISSUE THREAD

**Issue by martinlingstuyl** [Azure/Microsoft.Extensions.Caching.Cosmos#48] opened 2021-07-20 10:09 UTC
**Describe the bug**
I've installed the `Microsoft.Extensions.Caching.Cosmos` package and implemented it in a (Blazor Webassembly) asp.net core application. Next I access the session object like so:

```csharp
var session = HttpContext.Session;
if (!session.IsAvailable)
      await session.LoadAsync();
            
session.Set("test", System.Text.Encoding.UTF8.GetBytes("test"));
session.TryGetValue("test", out byte[] test);
```

As soon as I try to access the `Session` object in debug mode, there is some odd behavior. When I put a breakpoint on the `var session` line, I can see that the Session `Id` is Empty, and `IsAvailable` is false. `LoadAsync()` does not change this. If i execute a Set or a Get after that, my output window shows some connection errors:

```
DocDBTrace Information: 0 : RequestAsync failed: RID: dbs/<containername>/colls/<databasename>/docs/0693b8bd-20e2-8783-478d-f59023520f70, Resource Type: Document, Op: (operationType: Read, resourceType: Document), Address: rntbd://cdb-ms-prod-westeurope1-fd75.documents.azure.com:14012/apps/d87b8a42-9922-422e-8c91-e5e66bb6b76e/services/fe07a52b-7665-437b-8fa1-a6c27cc946da/partitions/3b498b24-1743-4fd3-9125-c6f14bb9095a/replicas/132711612049640158s/, Exception: System.Threading.ThreadAbortException: System error.
   at Microsoft.Azure.Documents.Rntbd.LoadBalancingPartition.RequestAsync(DocumentServiceRequest request, TransportAddressUri physicalAddress, ResourceOperation resourceOperation, Guid activityId, TransportRequestStats transportRequestStats)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Documents.Rntbd.LoadBalancingPartition.RequestAsync(DocumentServiceRequest request, TransportAddressUri physicalAddress, ResourceOperation resourceOperation, Guid activityId, TransportRequestStats transportRequestStats)
   at Microsoft.Azure.Documents.Rntbd.LoadBalancingChannel.RequestAsync(DocumentServiceRequest request, TransportAddressUri physicalAddress, ResourceOperation resourceOperation, Guid activityId, TransportRequestStats transportRequestStats)
   at Microsoft.Azure.Documents.Rntbd.TransportClient.InvokeStoreAsync(TransportAddressUri physicalAddress, ResourceOperation resourceOperation, DocumentServiceRequest request)
Microsoft.AspNetCore.Session.DistributedSession: Error: Session cache read exception, Key:0693b8bd-20e2-8783-478d-f59023520f70

System.Threading.ThreadAbortException: System error.
   at Microsoft.Extensions.Caching.Cosmos.CosmosCache.GetAsync(String key, CancellationToken token)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Extensions.Caching.Cosmos.CosmosCache.GetAsync(String key, CancellationToken token)
   at Microsoft.Extensions.Caching.Cosmos.CosmosCache.Get(String key)
   at Microsoft.AspNetCore.Session.DistributedSession.Load()
```

However: If i do put my breakpoint *after* the `session.Set()` or `session.TryGetValue` function call. The errors do *not* occur, and the session Id appears populated.

**To Reproduce**
1. Create a brandnew Blazor webassembly .net core project (with identity, etc)
2. Create a CosmosDb instance in azure and add the connection string to the project.
3. Add the CosmosDb extension Nuget package
4. Configure the pipeline as instructed in the documentation.
5. Add a few session calls in a controller and put breakpoints.

**Expected behavior**
Session Id should be populated, and debugging step by step should not raise these weird issues.

**Additional context**
I've tried this with a serverless CosmosDb, as well as with a Free Tier CosmosDb instance.

**Comment by ealsur** [comment] 2021-07-31 00:32
I cannot comment on webassembly debugging, or how it works with session state. Based on the documentation, the interaction with this caching library (or any other extension) happens only on the LoadAsync call (where it initializes) and on the Get/Set calls.

The exception you are sharing is not related to this library either, the error is a threadabort meaning that the runtime (asp.net core or webassembly) decided to kill the running thread. Most likely one or the other has a limit on the time a request can be processed and the fact that you are putting a breakpoint is holding it for longer than it is allowed. 

Some pointers though:

1. The LoadAsync on the documentation says it should be called always, it does not mention anything about checking IsAvailable https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-5.0
2. Use Async versions of Get/Set.
3. The Cosmos DB SDK uses TCP connections by default, I don't know how Webassembly supports TCP, you might want to switch to Gateway mode if Webassembly handles http better.

**Comment by martinlingstuyl** [comment] 2021-07-31 19:41
Hi @ealsur,

thanks for your response. 

Maybe it’s a bit misleading, but I’m not connecting from the browser clientside of blazor. I’m in fact debugging the server side, which is a web api that comes scaffolded alongside the client.. so it’s not really interesting that I discovered this on blazor persé.

Anyway: I’m sure it’s too easy here to say the exception is *unrelated* to the cosmos library, as the exception is thrown while executing it. Plus, the normal session implementation does not have issues at all. 

Thats my workaround of course: only using cosmos sessions in release builds.

thanks for the tip about ‘IsAvailable’ though: I read some blogs implementing this, but after some more searching, I agree with you this it should be called always. 

And thanks for the blog: interesting read!

**Comment by ealsur** [comment] 2021-08-02 15:46
@martinlingstuyl Thanks for the clarifications!

> Thats my workaround of course: only using cosmos sessions in release builds.

I am not sure I understand this, does this mean that on debug builds (no breakpoints) it does not work? Or that the issue is only happening when you put breakpoints?

Given that you mentioned that the Blazor backend is not on the browser (it's a normal Web API), then it might be limited by the Web API timeout to process the request (and generating the ThreadAbortException when the time is exceeded when placing the breakpoint). If you place the breakpoint after the networking interactions, can you confirm you do not get any errors?

**Comment by martinlingstuyl** [comment] 2021-08-05 18:36
Hi @ealsur 

As soon as I put breakpoints *before* cosmos session interaction, the session breaks.

So if I put breakpoints after the first get or set, everything works as it should. 

It doesn’t matter how much time you take for  stepping through the breakpoints. 

Of course, I do not want to continuously take this behavior into account when debugging, so I add the regular ‘DistributedSessionCache’ on debug builds.

**Comment by ealsur** [comment] 2021-08-05 20:07
@martinlingstuyl Got it, it seems that threadabort only happens if the breakpoint is put before. Not sure there is much that can be done in this package though, as the threadabort is coming from the OS. There is no source code in this repo or on the V3 SDK repo (https://github.com/Azure/azure-cosmos-dotnet-v3/) that throws these kind of exceptions, but rather they happen whenever there is a system signal of cancelling an executing thread (async network operations are different than in-memory operations that are used with the memory based cache because they can execute in other threads).

If when using the regular DistributedSessionCache (that I assume is the memory based) and putting the breaking before the operation, waiting several seconds (similar amount as with the Cosmos based cache) and continuing does not yield the same error, I'm really not sure what could be causing it. Something is signaling the thread abort.

I tried reproing on a WebAssembly ASP.NET Core application, the base template on VS, adding Cosmos cache and adding breakpoints before the interactions, was able to debug without issues:

![image](https://user-images.githubusercontent.com/1633401/128414197-1042ef38-a060-4478-8d74-681e53f7fa1f.png)

Not sure what kind of change can be done in this library for your case. If you can create a small repro project that we can use, we can try to identify something, but doesn't look like there is much.

**Comment by ealsur** [comment] 2021-08-12 06:43
Closing as cannot repro. Please re-open if further details arise.

**Closed by ealsur** 2021-08-12 06:43 UTC
Labels: needs-investigation
